# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-08T16:45:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class JobType(Enum):
    """
    - `regular` — a run is created at submit time.
    - `scheduled` — fires on a recurring or one-shot schedule.
      Submit stores the task list as a template on the job row;
      each scheduled fire produces a fresh Run. `schedule`
      field required. Read-only template: `addTasks` and
      `close` return 409. `rerun` (full or filtered) and `stop`
      are allowed.

    """

    REGULAR = "regular"
    SCHEDULED = "scheduled"


class JobStatus(Enum):
    """
    - `open` — initial run still accepting `addTasks`. Only
      meaningful while `latest_run.run_sequence == 1`.
    - `closed` — no more tasks accepted (created closed, or
      closed via `/close` / `addTasks{last_batch}` / `/rerun`).
    - `deleted` — async deletion in progress; the job disappears
      once it finishes.

    """

    OPEN = "open"
    CLOSED = "closed"
    DELETED = "deleted"


class ScheduleState(Enum):
    """
    Run/pause flag on a scheduled job. While `paused`, scheduled
    fires are skipped. Default at submit: `active`. Flip via
    `POST /v1/jobs/{id}/schedule/state`.

    """

    ACTIVE = "active"
    PAUSED = "paused"


class UpdateScheduleStateRequest(BaseModel):
    schedule_state: ScheduleState


class RunTrigger(Enum):
    """
    What set this run in motion. Always set.
    - `manual` — caller-initiated: `POST /jobs`, `POST /jobs/{id}/rerun`
      (any job type, full or `?status=`-filtered, manual fire of
      a scheduled job).
    - `scheduled` — automatic, fired by the configured
      schedule (recurring or one-shot).

    """

    MANUAL = "manual"
    SCHEDULED = "scheduled"


class RunStatus(Enum):
    """
    In-flight:
    - `running` — work queued / in flight.
    - `pending` — initial run of an open job, idle between batches.

    Terminal:
    - `completed` — natural finish.
    - `stopped` — caller called `POST /jobs/{id}/stop`. No new
      tasks are picked up; in-flight tasks may still finish.
      Result bodies are kept. `stats.completed < stats.total`
      signals "stopped early".
    - `failed` — the run was auto-failed on an account-level error
      (insufficient credits / inactive subscription). No new tasks
      are picked up; `failure_reason` carries the cause. Re-runnable
      once the account is resolved. Result bodies already produced
      are kept.
    - `deleted` — caller called
      `DELETE /v1/jobs/{id}/runs/{run_id}`. The run's result
      bodies and data are being deleted; once complete the run
      disappears.

    """

    RUNNING = "running"
    PENDING = "pending"
    COMPLETED = "completed"
    STOPPED = "stopped"
    FAILED = "failed"
    DELETED = "deleted"


class TaskStatus(Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    SUCCESSFUL = "successful"
    FAILED = "failed"


class ResultType(Enum):
    """
    Body format of a successful task result; matches the job's `format` 1:1.
    """

    HTML = "html"
    JSON = "json"
    MARKDOWN = "markdown"
    PLAINTEXT = "plaintext"
    PDF = "pdf"


class Format(Enum):
    """
    Derived server-side from `zenrows_params` at submit time.
    Precedence:
      - `response_type: markdown|plaintext|pdf` → matching format.
      - `autoparse: true`, `json_response: true`, or non-empty
        `css_extractor` → `json`.
      - otherwise → `html`.
    Stamped on every successful task result and used to set the
    right `Content-Type` when you fetch the content.

    """

    HTML = "html"
    JSON = "json"
    MARKDOWN = "markdown"
    PLAINTEXT = "plaintext"
    PDF = "pdf"


class TaskInput(BaseModel):
    external_id: Annotated[
        str | None, Field(max_length=128, pattern="^[A-Za-z0-9._-]+$")
    ] = None
    """
    Optional caller-supplied correlation id — typically an
    identifier from the caller's own system. Surfaced verbatim
    in result/content responses so callers can match results
    back to their records. **Not required to be unique** —
    callers may reuse the same value across tasks (e.g. when
    multiple scrapes correlate to the same upstream record).
    Independent of the server-
    assigned `task_id`.

    """
    url: AnyUrl
    """
    Must be http(s). Other schemes rejected at submit.
    """
    metadata: Annotated[dict[str, str] | None, Field(max_length=20)] = None
    zenrows_params: dict[str, str | bool | int] | None = None
    """
    Per-task scraper params. Override the job-level
    `zenrows_params` on key collision (task wins).

    """


class Status(Enum):
    """
    Initial state. `open` is only allowed for `regular` jobs;
    after the initial run, `open` has no meaning so the job
    is auto-closed.

    """

    OPEN = "open"
    CLOSED = "closed"


class AddTasksRequest(BaseModel):
    tasks: Annotated[list[TaskInput], Field(max_length=1000, min_length=1)]
    last_batch: bool | None = False
    """
    Set true on the final batch. Closes the job (status →
    `closed`) and marks the run's `last_batch_received`.

    """


class Spend(BaseModel):
    """
    Indicative `{credits, cost}` pair — what was charged for
    the scoped work. **Not billing-grade**; your account
    statement is authoritative. Use as a "how much did this
    cost?" indicator, not for reconciliation.

    """

    credits: Annotated[int, Field(ge=0)]
    cost: Annotated[float, Field(ge=0.0)]


class TaskSpend(BaseModel):
    """
    Per-task indicative spend with two roll-ups: `total`
    accumulates across every attempt (including retries),
    `last_attempt` carries just the most recent gateway call.
    On a task that succeeded on its first try the two are
    equal; on a retried task they diverge.

    """

    total: Spend
    last_attempt: Spend


class RunStats(BaseModel):
    total: int
    """
    Number of tasks in this run.
    """
    completed: int
    """
    successful + failed.
    """
    successful: int
    failed: int
    failure_reasons: Annotated[
        dict[str, int] | None, Field(examples=[{"blocked": 9, "gateway_error": 4}])
    ] = None
    """
    Coarse rollup of terminal failures keyed by a small public
    taxonomy. Lets you answer "what kinds of failures did I
    get?" without paging every error blob. Best-effort,
    indicative — omitted on runs with no failures yet and on
    runs that predate the feature.

    Vocabulary (the only keys that appear):
    - `auth_failed` — credentials or billing
    - `blocked` — anti-bot / policy denials
    - `bad_target` — target URL is the problem (bad host, 404, 410, too large)
    - `rate_limited` — target throttled the request
    - `timeout` — the scrape didn't complete in time
    - `gateway_error` — ZenRows-side transport / 5xx
    - `other` — anything else

    """
    spend: Spend | None = None
    """
    Indicative spend summed across every task attempt in
    this run. Absent on runs whose tasks predate this
    field (treat as zero).

    """


class PauseState(Enum):
    """
    Reversible-suspend flag, orthogonal to `status`.
    Omitted from responses when `active` / absent (legacy
    rows). Flip via `POST /jobs/{id}/pause` and
    `/resume`.

    """

    ACTIVE = "active"
    PAUSED = "paused"


class IngestStatus(Enum):
    """
    Present only on runs created by a large (202) submission.
    `pending` — task rows are still streaming into storage;
    reads may return partial pages and `addTasks` returns
    `409`. `done` — every accepted task row is visible.
    Omitted on runs whose tasks were written on the request
    path (201 submissions, `addTasks` batches, reruns).

    """

    PENDING = "pending"
    DONE = "done"


class FailureReason(Enum):
    """
    Present only when `status == failed`: the account-level
    cause of the auto-fail. `insufficient_credits` (out of
    credits) or `subscription_inactive` (subscription not
    active). Omitted otherwise. Distinct from
    `stats.failure_reasons` (the per-task rollup).

    """

    INSUFFICIENT_CREDITS = "insufficient_credits"
    SUBSCRIPTION_INACTIVE = "subscription_inactive"


class Run(BaseModel):
    run_id: str
    job_id: str
    run_sequence: Annotated[int, Field(ge=1)]
    status: RunStatus
    stats: RunStats
    last_batch_received: bool | None = None
    """
    Meaningful only for the initial run of an open job.
    Once true, `addTasks` is rejected and the run drains
    into `completed`.

    """
    pause_state: PauseState | None = None
    """
    Reversible-suspend flag, orthogonal to `status`.
    Omitted from responses when `active` / absent (legacy
    rows). Flip via `POST /jobs/{id}/pause` and
    `/resume`.

    """
    ingest_status: IngestStatus | None = None
    """
    Present only on runs created by a large (202) submission.
    `pending` — task rows are still streaming into storage;
    reads may return partial pages and `addTasks` returns
    `409`. `done` — every accepted task row is visible.
    Omitted on runs whose tasks were written on the request
    path (201 submissions, `addTasks` batches, reruns).

    """
    created_at: AwareDatetime
    updated_at: AwareDatetime
    failure_reason: FailureReason | None = None
    """
    Present only when `status == failed`: the account-level
    cause of the auto-fail. `insufficient_credits` (out of
    credits) or `subscription_inactive` (subscription not
    active). Omitted otherwise. Distinct from
    `stats.failure_reasons` (the per-task rollup).

    """


class Unit(Enum):
    MINUTE = "minute"
    HOUR = "hour"
    DAY = "day"


class ScheduleRate(BaseModel):
    """
    Interval-based fire policy — every N units.
    """

    every: Annotated[int, Field(examples=[15], ge=1)]
    unit: Unit


class TimesOfDayItem(RootModel[str]):
    root: Annotated[str, Field(pattern="^([01][0-9]|2[0-3]):00$")]


class Day(Enum):
    MON = "mon"
    TUE = "tue"
    WED = "wed"
    THU = "thu"
    FRI = "fri"
    SAT = "sat"
    SUN = "sun"


class Weekly(BaseModel):
    days: Annotated[list[Day], Field(examples=[["mon", "wed", "fri"]], min_length=1)]


class Day1(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=31)]


class Monthly(BaseModel):
    days: Annotated[list[Day1], Field(examples=[[1, 15]], min_length=1)]


class ScheduleCadence(BaseModel):
    """
    Picks which days the schedule fires on. Exactly one of
    `daily`, `weekly`, `monthly` must be set.

    """

    daily: dict[str, Any] | None = None
    """
    Fire every day. No knobs.
    """
    weekly: Weekly | None = None
    monthly: Monthly | None = None


class ListJobRunsResponse(BaseModel):
    runs: list[Run]
    next_cursor: str | None = None


class WebhookConfig(BaseModel):
    """
    Webhook delivery config for `run.completed` / `run.failed`. Returned on
    `GET /v1/jobs/{id}` (inline under `webhook`) and on
    `GET /v1/jobs/{id}/webhook`. `PUT` requires both fields —
    no defaulting at the mutate boundary (otherwise toggling
    `url` would silently disable signing). Submit body accepts
    the same shape with `signature` optional (defaults `false`).

    """

    url: AnyUrl
    """
    HTTPS only. Host must resolve via DNS within 1 second
    (1+ A/AAAA record).

    """
    signature: bool
    """
    Opt-in HMAC signing. When `true`, each delivery is signed
    with the org's active HMAC key
    (`POST /v1/hmac/keys/rotate`) and carries
    `X-Signature: t=<unix>,v1=<hex>,kid=<active>`. The signed
    input is `t + "." + raw_body`, HMAC-SHA256. When `false`,
    deliveries carry **no** `X-Signature` header — header
    absence is the signal.

    """


class TestWebhookRequest(BaseModel):
    """
    Body for `POST /v1/webhook/test`. Same shape as the submit-time
    `webhook` field; `signature` is optional and defaults `false`.

    """

    url: AnyUrl
    """
    HTTPS only. Host must resolve via DNS within 1 second.
    Identical validation to the submit/PUT webhook URL.

    """
    signature: bool | None = False
    """
    When `true`, the test event is signed with the org's
    active HMAC key — same `X-Signature: t,v1,kid` header
    real deliveries use. Returns `400
    webhook_signing_requires_active_key` when no active key
    exists.

    """


class TestWebhookResponse(BaseModel):
    """
    Outcome of the synthetic test dispatch. HTTP status is always
    `200` when the request was validated — the receiver outcome
    is in the body. The synthetic envelope uses `event_type:
    "webhook.test"` and stable sentinel IDs (`job_id`/`run_id` =
    `"test"`) so receivers can recognise and discard test traffic.

    """

    delivered: bool
    """
    `true` iff the receiver responded with a 2xx status. `false`
    on non-2xx, timeout, or transport error.

    """
    event_id: str
    """
    ULID of the synthetic event. Different on every call so
    receivers' dedup tables don't suppress repeated tests.

    """
    status_code: int | None = None
    """
    HTTP status returned by the receiver. Absent on timeout or
    transport error (no response was received).

    """
    error: str | None = None
    """
    Human-readable reason when `delivered: false`. Same
    vocabulary as real webhook deliveries
    (`http_4xx:<code>`, `http_5xx:<code>`, `timeout`,
    `transport_error:<detail>`). Absent on success.

    """
    elapsed_ms: int
    """
    Wall-clock duration of the receiver POST in milliseconds.
    """


class FileInputColumnRef1(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]
    """
    Either a column name (string) — requires `csv.header: true` —
    or a 0-based column index (integer). Other shapes are
    rejected at create-time.

    """


class FileInputColumnRef2(RootModel[int]):
    root: Annotated[int, Field(ge=0)]
    """
    Either a column name (string) — requires `csv.header: true` —
    or a 0-based column index (integer). Other shapes are
    rejected at create-time.

    """


class Fields(BaseModel):
    """
    Map from canonical task field → CSV column. Only
    `url` (required) and `external_id` (optional) are
    accepted. Each value is a column index (int) or a
    column name (string, requires `header: true`).

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    url: FileInputColumnRef1 | FileInputColumnRef2
    """
    Either a column name (string) — requires `csv.header: true` —
    or a 0-based column index (integer). Other shapes are
    rejected at create-time.

    """
    external_id: FileInputColumnRef1 | FileInputColumnRef2 | None = None
    """
    Either a column name (string) — requires `csv.header: true` —
    or a 0-based column index (integer). Other shapes are
    rejected at create-time.

    """


class Csv(BaseModel):
    delimiter: Annotated[str | None, Field(max_length=1, min_length=1)] = ","
    """
    Single-character field delimiter.
    """
    quote: Annotated[str | None, Field(max_length=1, min_length=1)] = '"'
    """
    Single-character quoting character.
    """
    header: bool | None = False
    """
    When true, the first CSV row is consumed as a header
    row and `csv.fields.*` values may be column names.

    """
    fields: Fields
    """
    Map from canonical task field → CSV column. Only
    `url` (required) and `external_id` (optional) are
    accepted. Each value is a column index (int) or a
    column name (string, requires `header: true`).

    """


class CreateJobInputRequest(BaseModel):
    type: Literal["csv"]
    """
    Only `csv` is supported in v1.
    """
    csv: Csv | None = None


class FileInputUploadTarget(BaseModel):
    method: Literal["PUT"]
    url: AnyUrl
    """
    Presigned PUT URL. Caller MUST send the body with the
    exact `Content-Type` shown in `headers` — the signature
    binds the content-type.

    """
    headers: Annotated[
        dict[str, str] | None, Field(examples=[{"Content-Type": "text/csv"}])
    ] = None
    expires_at: AwareDatetime
    """
    PUT URL TTL (~30 min).
    """


class CreateJobInputResponse(BaseModel):
    file_input_id: str
    upload: FileInputUploadTarget
    expires_at: AwareDatetime
    """
    24 h slot lifetime — beyond this the slot and its uploaded
    body are removed and the `file_input_id` returns 404.

    """


class HMACKeyMeta(BaseModel):
    """
    Public view of one HMAC key — id + creation time. Never
    includes secret material; that's only returned at /rotate.

    """

    kid: Annotated[str, Field(pattern="^[0-9A-HJKMNP-TV-Z]{26}$")]
    """
    ULID identifying this key. Stable for the life of the slot; a new candidate gets a new kid.
    """
    created_at: AwareDatetime


class HMACKeyList(BaseModel):
    """
    Slots populated at the time of the call.
    """

    active: HMACKeyMeta | None = None
    candidate: HMACKeyMeta | None = None


class HMACKeyCreated(BaseModel):
    """
    Response to `/rotate`. `secret` is base64-encoded raw key
    material. **This is the ONLY response that ever contains
    the secret value** — capture it now or generate a new one
    via another /rotate call.

    """

    kid: Annotated[str, Field(pattern="^[0-9A-HJKMNP-TV-Z]{26}$")]
    secret: str
    """
    Base64-encoded 32-byte HMAC key.
    """
    created_at: AwareDatetime


class HMACKeyFinalized(BaseModel):
    """
    Response to `/rotate/finalize`. No secret.
    """

    active_kid: Annotated[str, Field(pattern="^[0-9A-HJKMNP-TV-Z]{26}$")]
    created_at: AwareDatetime


class Reason(Enum):
    MALFORMED_URL = "malformed_url"
    UNSUPPORTED_SCHEME = "unsupported_scheme"
    MISSING_HOST = "missing_host"
    URL_TOO_LONG = "url_too_long"
    METADATA_TOO_LARGE = "metadata_too_large"
    METADATA_KEY_INVALID = "metadata_key_invalid"
    INVALID_EXTERNAL_ID = "invalid_external_id"
    UNKNOWN_PARAM = "unknown_param"
    INVALID_PARAM_VALUE = "invalid_param_value"


class InvalidTask(BaseModel):
    index: int
    reason: Reason
    value: str | None = None
    """
    Offending input. For URL / metadata reasons this is
    a redacted/truncated form of the bad value. For
    `unknown_param` / `invalid_param_value` this is the
    param key.

    """


class Problem(BaseModel):
    """
    RFC 7807 Problem Details.

    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: AnyUrl
    title: str
    status: int
    detail: str | None = None
    code: str
    instance: str | None = None
    invalid_tasks: list[InvalidTask] | None = None
    """
    Present on validation errors.
    """


class ExportStatus(Enum):
    """
    Lifecycle state of a results export.
    * `pending` — export accepted, not started yet.
    * `running` — the zip is being produced.
    * `completed` — `download_url` will be present.
    * `failed`   — `error` carries the reason.

    """

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class StartExportResponse(BaseModel):
    """
    Returned by `startResultsExport`.
    """

    export_id: Annotated[str, Field(pattern="^[0-9A-HJKMNP-TV-Z]{26}$")]
    """
    ULID identifying this export. Use it for `getResultsExport`.
    """
    status: ExportStatus
    created_at: AwareDatetime
    expires_at: AwareDatetime
    """
    12 h after `created_at`. Past this point the export and
    its download are removed and the export id 404s.

    """


class Export(BaseModel):
    """
    Polled view of a results export. `download_url` is presigned
    fresh on every successful poll — stash the metadata, but
    re-fetch the URL right before you download.

    """

    export_id: Annotated[str, Field(pattern="^[0-9A-HJKMNP-TV-Z]{26}$")]
    status: ExportStatus
    error: str | None = None
    """
    Non-empty only when `status = failed`. Stable strings —
    e.g. `"results are larger then 1 gb"` when the combined
    results exceed the 1 GiB cap.

    """
    download_url: AnyUrl | None = None
    """
    Presigned download URL for the zipped run results.
    Present only when `status = completed`. Short-lived — the
    server mints a new one on every poll.

    """
    created_at: AwareDatetime
    expires_at: AwareDatetime
    """
    12 h after `created_at`. The download is unavailable
    after this point.

    """


class SubmitJobResponse(BaseModel):
    job_id: str
    status: JobStatus
    latest_run: Run | None = None
    """
    Absent for `scheduled` jobs that haven't fired yet.
    """
    accepted_tasks: int
    webhook: WebhookConfig | None = None
    """
    Echo of the webhook config persisted on the job (when
    one was supplied). Omitted when no webhook was set.

    """


class AddTasksResponse(BaseModel):
    accepted_tasks: int
    job_status: JobStatus
    latest_run: Run


class RerunJobResponse(BaseModel):
    job_id: str
    status: JobStatus
    latest_run: Run
    rerun_of: str | None = None
    """
    `run_id` of the previous run that was replayed. Empty on
    the first manual fire of a scheduled job (no prior run).

    """
    retried_tasks: int
    """
    Number of rows reset to `pending` and re-enqueued. Equals
    `latest_run.stats.total` for a full rerun; equals the
    filter-matched count for a `?status=` partial retry.

    """
    inherited_tasks: int
    """
    Number of rows copied verbatim from the previous run with
    `source_run_id` stamped. Zero for a full rerun; non-zero
    only when `?status=` is set.

    """


class ScheduleCalendar(BaseModel):
    """
    Calendar-style fire policy. Fires at every `times_of_day`
    entry on every day matching the cadence.

    """

    times_of_day: Annotated[
        list[TimesOfDayItem], Field(examples=[["09:00", "18:00"]], min_length=1)
    ]
    """
    Wall-clock times on a 24-hour clock, full hours only
    (`"09:00"`, `"18:00"`). Minute granularity is rejected
    with 400.

    """
    cadence: ScheduleCadence


class TaskResult(BaseModel):
    task_id: str
    external_id: str | None = None
    """
    Caller-supplied correlation id from submit/AddTasks.
    Omitted when the caller did not supply one.

    """
    run_id: str
    url: AnyUrl
    metadata: Annotated[dict[str, str] | None, Field(max_length=20)] = None
    status: TaskStatus
    type: ResultType | None = None
    result_url: str | None = None
    """
    2-hour presigned download URL for the result body, or a
    `/v1/jobs/<id>/runs/<run>/tasks/<tid>/content` URL you can
    fetch directly. Empty for non-successful tasks.

    """
    error: Problem | None = None
    """
    Present on failed tasks. The scraping engine's error
    response as Problem JSON, or a synthesised envelope with
    `code: "gateway_unreachable"` when it couldn't be reached.

    """
    source_run_id: str | None = None
    """
    Set when this row was copied from another run by
    `/rerun?status=`. The row is terminal at creation, is
    never re-executed, and its `result_url` resolves to the
    source run's stored result. On chained retries,
    `source_run_id` chases back to the run that actually
    owns the result. Empty for normally-executed rows.

    """
    spend: TaskSpend | None = None


class ListResultsResponse(BaseModel):
    results: list[TaskResult]
    next_cursor: str | None = None


class TaskHistoryEvent(BaseModel):
    started_at: AwareDatetime
    ended_at: AwareDatetime
    attempt: Annotated[int, Field(ge=1)]
    """
    1-indexed attempt within the run.
    """
    error: Problem | None = None
    spend: Spend | None = None
    """
    Indicative spend charged for this single attempt. Zero
    on attempts that didn't reach the scraping engine or
    were not charged.

    """


class TaskHistoryResponse(BaseModel):
    events: list[TaskHistoryEvent]


class JobSchedule(BaseModel):
    """
    Structured scheduling block attached to `type: scheduled`
    jobs. Exactly one of `at`, `rate`, or `calendar` must be
    set.

    """

    at: Annotated[str | None, Field(examples=["2026-09-01T09:00:00"])] = None
    """
    One-shot fire at a specific wall-clock timestamp.
    Mutually exclusive with `rate` and `schedule`.

    **Must be tz-naive** — no trailing `Z`, no offset. The
    sibling `timezone` field (mandatory) is the single
    authoritative interpreter. This keeps DST transitions
    deterministic.

    """
    rate: ScheduleRate | None = None
    calendar: ScheduleCalendar | None = None
    timezone: Annotated[str | None, Field(examples=["Europe/Berlin"])] = None
    """
    IANA timezone name (e.g. `Europe/Berlin`, `UTC`).
    **Required** when `at` or `calendar` is set;
    ignored by `rate` (interval-based, no wall-clock
    meaning). Anchoring wall-clock times to a named zone
    (rather than a UTC offset baked into the string) keeps
    DST transitions deterministic.

    """


class Job(BaseModel):
    job_id: str
    type: JobType
    status: JobStatus
    format: Format | None = None
    zenrows_params: dict[str, str] | None = None
    """
    Stored canonical form — values are always strings even
    though submit accepts any JSON scalar (see ScraperParams).

    """
    external_id: str | None = None
    """
    Caller-supplied correlation id passed at submit (omitted
    when the caller did not supply one). Not server-enforced
    unique.

    """
    name: str | None = None
    """
    Optional human label passed at submit (omitted when the
    caller did not supply one). Free-form, up to 100 chars.

    """
    metadata: Annotated[dict[str, str] | None, Field(max_length=20)] = None
    schedule: JobSchedule | None = None
    """
    Schedule block — present only for `type: scheduled`
    jobs.

    """
    next_scheduled_run: AwareDatetime | None = None
    """
    Server-computed timestamp of the next expected fire,
    stamped at submit and re-stamped on every fire. `null`
    for non-scheduled jobs and for one-shot `at(...)`
    schedules that have already fired. Stays computed when
    `schedule_state == paused` — "what would fire next if
    you resumed."

    """
    schedule_state: ScheduleState | None = None
    """
    Set only for `type: scheduled`. Default `active` at
    submit; flip via `POST /v1/jobs/{id}/schedule/state`.

    """
    webhook: WebhookConfig | None = None
    """
    Webhook delivery config. Present iff a
    webhook is configured. Mutable via `PUT/DELETE
    /v1/jobs/{id}/webhook`; `signature` never appears
    alone — the whole `webhook` key is omitted when no
    URL is set.

    """
    latest_run: Run | None = None
    """
    Snapshot projection of the latest run. Absent for
    `scheduled` jobs that haven't fired yet.

    """
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ListJobsResponse(BaseModel):
    jobs: list[Job]
    next_cursor: str | None = None


class SubmitJobRequest(BaseModel):
    type: JobType | None = "regular"
    status: Status | None = "closed"
    """
    Initial state. `open` is only allowed for `regular` jobs;
    after the initial run, `open` has no meaning so the job
    is auto-closed.

    """
    zenrows_params: dict[str, str | bool | int] | None = None
    """
    Job-level scraper params, applied to every task of every
    run of the job. Each task can override individual keys
    via its own `zenrows_params` (task wins on collision).

    """
    schedule: JobSchedule | None = None
    """
    Schedule block for `type: scheduled`. Required there,
    ignored otherwise.

    """
    tasks: Annotated[list[TaskInput] | None, Field(max_length=1000, min_length=0)] = (
        None
    )
    """
    Required for closed jobs (1–1000) unless `file_input_id`
    is provided. Optional for open jobs — may be empty if the
    caller will follow up with `addTasks`. Mutually exclusive
    with `file_input_id`.

    """
    file_input_id: str | None = None
    """
    Reference to a previously-uploaded CSV input (see
    `POST /v1/job_inputs`). Mutually exclusive with `tasks`.
    Eligible only for regular-closed and scheduled job types.
    The uploaded CSV is parsed under the saved spec; its rows
    become tasks (regular-closed) or template_tasks
    (scheduled).

    """
    external_id: Annotated[
        str | None, Field(max_length=128, pattern="^[A-Za-z0-9._-]+$")
    ] = None
    """
    Optional caller-supplied correlation id for the job —
    same semantics as `task.external_id`. Shape-checked,
    **not** required to be unique. Surfaced verbatim in
    `getJob` / `listJobs` responses.

    """
    name: Annotated[str | None, Field(max_length=100)] = None
    """
    Optional human-readable label for the job. Free-form —
    no shape rules. Up to 100 characters. Surfaced verbatim
    in `getJob` / `listJobs` responses. No uniqueness, no
    indexing; cannot be changed after submit.

    """
    metadata: Annotated[dict[str, str] | None, Field(max_length=20)] = None
    webhook: WebhookConfig | None = None
    """
    Optional `run.completed` / `run.failed` delivery config.
    A terminal run fires `run.completed` on a natural finish, or
    `run.failed` (with `failure_reason` + partial stats) when the
    run auto-fails on an account-level error. `signature`
    defaults to `false` here so first-time integrations
    don't need an HMAC key. Config is mutable post-submit
    via `PUT /v1/jobs/{id}/webhook` and `DELETE
    /v1/jobs/{id}/webhook`; the current config is surfaced
    on `GET /v1/jobs/{id}`.

    """
